-- Prisma's `uuid()` default is generated by the client. The preceding
-- backfill migrations used a temporary PostgreSQL default so existing rows
-- could be populated while adding a NOT NULL column. Remove those database
-- defaults after the backfill to match every other public ID column and keep
-- the migration history aligned with the Prisma schema.
ALTER TABLE "app"."merchandising_placements"
  ALTER COLUMN "public_id" DROP DEFAULT;

ALTER TABLE "app"."roles"
  ALTER COLUMN "public_id" DROP DEFAULT;
