-- CreateEnum
CREATE TYPE "app"."catalog_status" AS ENUM ('draft', 'active', 'archived');

-- CreateEnum
CREATE TYPE "app"."media_kind" AS ENUM ('image', 'video', 'document');

-- CreateEnum
CREATE TYPE "app"."product_media_role" AS ENUM ('primary', 'gallery', 'swatch', 'video', 'document');

-- CreateEnum
CREATE TYPE "app"."price_kind" AS ENUM ('regular', 'sale');

-- CreateEnum
CREATE TYPE "app"."inventory_movement_type" AS ENUM ('receipt', 'adjustment', 'reservation', 'release', 'sale', 'return', 'damage');

-- CreateEnum
CREATE TYPE "app"."inventory_reservation_status" AS ENUM ('active', 'released', 'consumed', 'expired');

-- CreateEnum
CREATE TYPE "app"."cart_status" AS ENUM ('active', 'converted', 'abandoned', 'expired');

-- CreateEnum
CREATE TYPE "app"."order_status" AS ENUM ('draft', 'pending_payment', 'confirmed', 'processing', 'completed', 'canceled');

-- CreateEnum
CREATE TYPE "app"."order_payment_status" AS ENUM ('unpaid', 'pending', 'partially_paid', 'paid', 'partially_refunded', 'refunded', 'failed', 'voided');

-- CreateEnum
CREATE TYPE "app"."fulfillment_status" AS ENUM ('unfulfilled', 'partial', 'fulfilled', 'returned', 'canceled');

-- CreateEnum
CREATE TYPE "app"."order_address_kind" AS ENUM ('shipping', 'billing');

-- CreateEnum
CREATE TYPE "app"."payment_method" AS ENUM ('nowpayments', 'wire_transfer', 'zelle', 'other_manual');

-- CreateEnum
CREATE TYPE "app"."payment_status" AS ENUM ('created', 'pending', 'awaiting_confirmation', 'confirmed', 'partially_refunded', 'refunded', 'failed', 'expired', 'canceled');

-- CreateEnum
CREATE TYPE "app"."manual_payment_proof_status" AS ENUM ('pending', 'approved', 'rejected');

-- CreateEnum
CREATE TYPE "app"."shipment_status" AS ENUM ('draft', 'label_created', 'in_transit', 'delivered', 'exception', 'returned', 'canceled');

-- CreateEnum
CREATE TYPE "app"."tracking_event_status" AS ENUM ('info', 'label_created', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'exception', 'returned');

-- CreateEnum
CREATE TYPE "app"."inquiry_source" AS ENUM ('web', 'whatsapp', 'email', 'phone', 'other');

-- CreateEnum
CREATE TYPE "app"."inquiry_status" AS ENUM ('open', 'in_progress', 'waiting_customer', 'resolved', 'closed');

-- CreateEnum
CREATE TYPE "app"."content_status" AS ENUM ('draft', 'published', 'archived');

-- CreateEnum
CREATE TYPE "app"."content_format" AS ENUM ('markdown', 'rich_text', 'html');

-- CreateTable
CREATE TABLE "app"."categories" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "parent_id" BIGINT,
    "slug" VARCHAR(180) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "status" "app"."catalog_status" NOT NULL DEFAULT 'draft',
    "position" INTEGER NOT NULL DEFAULT 0,
    "published_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."tags" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "slug" VARCHAR(180) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "status" "app"."catalog_status" NOT NULL DEFAULT 'draft',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."products" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "slug" VARCHAR(220) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "subtitle" VARCHAR(255),
    "description" TEXT,
    "brand" VARCHAR(160),
    "status" "app"."catalog_status" NOT NULL DEFAULT 'draft',
    "is_featured" BOOLEAN NOT NULL DEFAULT false,
    "published_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."product_variants" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "product_id" BIGINT NOT NULL,
    "sku" VARCHAR(120) NOT NULL,
    "barcode" VARCHAR(120),
    "title" VARCHAR(255) NOT NULL,
    "status" "app"."catalog_status" NOT NULL DEFAULT 'draft',
    "option_values" JSONB,
    "weight_grams" INTEGER,
    "length_millimeters" INTEGER,
    "width_millimeters" INTEGER,
    "height_millimeters" INTEGER,
    "requires_shipping" BOOLEAN NOT NULL DEFAULT true,
    "track_inventory" BOOLEAN NOT NULL DEFAULT true,
    "position" INTEGER NOT NULL DEFAULT 0,
    "published_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "product_variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."product_categories" (
    "product_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_categories_pkey" PRIMARY KEY ("product_id","category_id")
);

-- CreateTable
CREATE TABLE "app"."product_tags" (
    "product_id" BIGINT NOT NULL,
    "tag_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_tags_pkey" PRIMARY KEY ("product_id","tag_id")
);

-- CreateTable
CREATE TABLE "app"."media" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "kind" "app"."media_kind" NOT NULL,
    "storage_provider" VARCHAR(80) NOT NULL,
    "storage_key" TEXT NOT NULL,
    "public_url" TEXT,
    "alt_text" VARCHAR(500),
    "mime_type" VARCHAR(160),
    "width" INTEGER,
    "height" INTEGER,
    "size_bytes" BIGINT,
    "checksum" VARCHAR(128),
    "is_private" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "media_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."product_media" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "product_id" BIGINT NOT NULL,
    "variant_id" BIGINT,
    "media_id" BIGINT NOT NULL,
    "role" "app"."product_media_role" NOT NULL DEFAULT 'gallery',
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_media_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."prices" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "variant_id" BIGINT NOT NULL,
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "kind" "app"."price_kind" NOT NULL DEFAULT 'regular',
    "amount_minor" BIGINT NOT NULL,
    "country_code" CHAR(2),
    "tax_inclusive" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "starts_at" TIMESTAMPTZ(3),
    "ends_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "prices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."inquiries" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "inquiry_number" VARCHAR(50) NOT NULL,
    "customer_user_id" UUID,
    "assigned_to_user_id" UUID,
    "order_id" BIGINT,
    "product_id" BIGINT,
    "source" "app"."inquiry_source" NOT NULL,
    "status" "app"."inquiry_status" NOT NULL DEFAULT 'open',
    "customer_name" VARCHAR(255),
    "customer_email" VARCHAR(320),
    "customer_phone" VARCHAR(32),
    "subject" VARCHAR(255) NOT NULL,
    "message" TEXT NOT NULL,
    "resolved_at" TIMESTAMPTZ(3),
    "closed_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "inquiries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."whatsapp_contact_intents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "user_id" UUID,
    "inquiry_id" BIGINT,
    "cart_id" BIGINT,
    "order_id" BIGINT,
    "product_id" BIGINT,
    "source_path" TEXT,
    "message_template_key" VARCHAR(120),
    "prefilled_message" TEXT,
    "context_snapshot" JSONB,
    "opened_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "whatsapp_contact_intents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."internal_notes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "author_user_id" UUID NOT NULL,
    "customer_user_id" UUID,
    "inquiry_id" BIGINT,
    "order_id" BIGINT,
    "payment_id" BIGINT,
    "shipment_id" BIGINT,
    "body" TEXT NOT NULL,
    "is_pinned" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "internal_notes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."blog_posts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "slug" VARCHAR(220) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "excerpt" TEXT,
    "body" TEXT NOT NULL,
    "format" "app"."content_format" NOT NULL DEFAULT 'markdown',
    "status" "app"."content_status" NOT NULL DEFAULT 'draft',
    "author_user_id" UUID,
    "hero_media_id" BIGINT,
    "published_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "blog_posts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."pages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "slug" VARCHAR(220) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "body" TEXT NOT NULL,
    "format" "app"."content_format" NOT NULL DEFAULT 'markdown',
    "status" "app"."content_status" NOT NULL DEFAULT 'draft',
    "author_user_id" UUID,
    "hero_media_id" BIGINT,
    "published_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "pages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."faqs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "slug" VARCHAR(220) NOT NULL,
    "question" VARCHAR(500) NOT NULL,
    "answer" TEXT NOT NULL,
    "category" VARCHAR(160),
    "status" "app"."content_status" NOT NULL DEFAULT 'draft',
    "position" INTEGER NOT NULL DEFAULT 0,
    "author_user_id" UUID,
    "published_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "faqs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."navigations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "key" VARCHAR(100) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "status" "app"."content_status" NOT NULL DEFAULT 'draft',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "navigations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."navigation_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "navigation_id" BIGINT NOT NULL,
    "parent_id" BIGINT,
    "page_id" BIGINT,
    "category_id" BIGINT,
    "product_id" BIGINT,
    "label" VARCHAR(160) NOT NULL,
    "url" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "open_in_new_tab" BOOLEAN NOT NULL DEFAULT false,
    "is_visible" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "navigation_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."carriers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "code" VARCHAR(80) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "tracking_url_template" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "carriers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."shipments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "shipment_number" VARCHAR(50) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "carrier_id" BIGINT,
    "status" "app"."shipment_status" NOT NULL DEFAULT 'draft',
    "service_level" VARCHAR(120),
    "tracking_number" VARCHAR(180),
    "label_url" TEXT,
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "shipping_cost_minor" BIGINT,
    "shipped_at" TIMESTAMPTZ(3),
    "delivered_at" TIMESTAMPTZ(3),
    "canceled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "shipments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."packages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "package_number" INTEGER NOT NULL,
    "weight_grams" INTEGER,
    "length_millimeters" INTEGER,
    "width_millimeters" INTEGER,
    "height_millimeters" INTEGER,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "packages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."shipment_items" (
    "shipment_id" BIGINT NOT NULL,
    "order_item_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "shipment_items_pkey" PRIMARY KEY ("shipment_id","order_item_id")
);

-- CreateTable
CREATE TABLE "app"."tracking_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "carrier_event_id" VARCHAR(255),
    "status" "app"."tracking_event_status" NOT NULL DEFAULT 'info',
    "message" TEXT,
    "location" VARCHAR(255),
    "raw_payload" JSONB,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tracking_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."inventory_locations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "code" VARCHAR(80) NOT NULL,
    "name" VARCHAR(180) NOT NULL,
    "country_code" CHAR(2) NOT NULL DEFAULT 'US',
    "region" VARCHAR(120),
    "city" VARCHAR(120),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "inventory_locations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."inventory_levels" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "variant_id" BIGINT NOT NULL,
    "location_id" BIGINT NOT NULL,
    "on_hand_quantity" INTEGER NOT NULL DEFAULT 0,
    "reserved_quantity" INTEGER NOT NULL DEFAULT 0,
    "safety_stock_quantity" INTEGER NOT NULL DEFAULT 0,
    "allow_backorder" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "inventory_levels_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."inventory_movements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "inventory_level_id" BIGINT NOT NULL,
    "type" "app"."inventory_movement_type" NOT NULL,
    "quantity_delta" INTEGER NOT NULL,
    "on_hand_after" INTEGER NOT NULL,
    "reference_type" VARCHAR(80),
    "reference_id" VARCHAR(255),
    "reason" TEXT,
    "created_by_user_id" UUID,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inventory_movements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."inventory_reservations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "inventory_level_id" BIGINT NOT NULL,
    "cart_item_id" BIGINT,
    "order_item_id" BIGINT,
    "status" "app"."inventory_reservation_status" NOT NULL DEFAULT 'active',
    "quantity" INTEGER NOT NULL,
    "expires_at" TIMESTAMPTZ(3),
    "released_at" TIMESTAMPTZ(3),
    "consumed_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "inventory_reservations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."payment_method_configs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "method" "app"."payment_method" NOT NULL,
    "display_name" VARCHAR(160) NOT NULL,
    "is_enabled" BOOLEAN NOT NULL DEFAULT false,
    "public_instructions" TEXT,
    "credential_env_prefix" VARCHAR(120),
    "setting_key" VARCHAR(160),
    "updated_by_user_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "payment_method_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."payments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "order_id" BIGINT NOT NULL,
    "method" "app"."payment_method" NOT NULL,
    "status" "app"."payment_status" NOT NULL DEFAULT 'created',
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "amount_minor" BIGINT NOT NULL,
    "crypto_currency" VARCHAR(20),
    "crypto_amount" DECIMAL(36,18),
    "exchange_rate" DECIMAL(36,18),
    "provider_payment_id" VARCHAR(255),
    "provider_status" VARCHAR(120),
    "checkout_url" TEXT,
    "expires_at" TIMESTAMPTZ(3),
    "confirmed_at" TIMESTAMPTZ(3),
    "failed_at" TIMESTAMPTZ(3),
    "canceled_at" TIMESTAMPTZ(3),
    "metadata" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."payment_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "payment_id" BIGINT NOT NULL,
    "provider_event_id" VARCHAR(255),
    "event_type" VARCHAR(160) NOT NULL,
    "status_before" "app"."payment_status",
    "status_after" "app"."payment_status",
    "amount_minor" BIGINT,
    "crypto_amount" DECIMAL(36,18),
    "raw_payload" JSONB,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payment_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."manual_payment_proofs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "payment_id" BIGINT NOT NULL,
    "media_id" BIGINT,
    "submitted_by_user_id" UUID,
    "reviewed_by_user_id" UUID,
    "reference_number" VARCHAR(255),
    "amount_minor" BIGINT NOT NULL,
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "note" TEXT,
    "status" "app"."manual_payment_proof_status" NOT NULL DEFAULT 'pending',
    "reviewed_at" TIMESTAMPTZ(3),
    "review_note" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "manual_payment_proofs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."carts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "user_id" UUID,
    "anonymous_token_hash" CHAR(64),
    "status" "app"."cart_status" NOT NULL DEFAULT 'active',
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "expires_at" TIMESTAMPTZ(3),
    "abandoned_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "carts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."cart_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cart_id" BIGINT NOT NULL,
    "variant_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price_minor" BIGINT,
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "customizations" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "cart_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "order_number" VARCHAR(40) NOT NULL,
    "cart_id" BIGINT,
    "user_id" UUID,
    "customer_email" VARCHAR(320) NOT NULL,
    "customer_phone" VARCHAR(32),
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "status" "app"."order_status" NOT NULL DEFAULT 'draft',
    "payment_status" "app"."order_payment_status" NOT NULL DEFAULT 'unpaid',
    "fulfillment_status" "app"."fulfillment_status" NOT NULL DEFAULT 'unfulfilled',
    "subtotal_minor" BIGINT NOT NULL DEFAULT 0,
    "discount_minor" BIGINT NOT NULL DEFAULT 0,
    "shipping_minor" BIGINT NOT NULL DEFAULT 0,
    "tax_minor" BIGINT NOT NULL DEFAULT 0,
    "total_minor" BIGINT NOT NULL DEFAULT 0,
    "customer_note" TEXT,
    "placed_at" TIMESTAMPTZ(3),
    "confirmed_at" TIMESTAMPTZ(3),
    "completed_at" TIMESTAMPTZ(3),
    "canceled_at" TIMESTAMPTZ(3),
    "cancellation_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."order_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "product_id" BIGINT,
    "variant_id" BIGINT,
    "product_name" VARCHAR(255) NOT NULL,
    "product_slug" VARCHAR(220),
    "variant_name" VARCHAR(255),
    "sku" VARCHAR(120) NOT NULL,
    "option_values" JSONB,
    "quantity" INTEGER NOT NULL,
    "fulfilled_quantity" INTEGER NOT NULL DEFAULT 0,
    "unit_price_minor" BIGINT NOT NULL,
    "discount_minor" BIGINT NOT NULL DEFAULT 0,
    "tax_minor" BIGINT NOT NULL DEFAULT 0,
    "line_total_minor" BIGINT NOT NULL,
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "weight_grams" INTEGER,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."order_addresses" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "kind" "app"."order_address_kind" NOT NULL,
    "recipient_name" VARCHAR(255) NOT NULL,
    "company" VARCHAR(255),
    "line1" VARCHAR(255) NOT NULL,
    "line2" VARCHAR(255),
    "city" VARCHAR(120) NOT NULL,
    "region" VARCHAR(120) NOT NULL,
    "postal_code" VARCHAR(20) NOT NULL,
    "country_code" CHAR(2) NOT NULL DEFAULT 'US',
    "phone" VARCHAR(32),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_addresses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."seo_metadata" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "product_id" BIGINT,
    "category_id" BIGINT,
    "blog_post_id" BIGINT,
    "page_id" BIGINT,
    "faq_id" BIGINT,
    "open_graph_media_id" BIGINT,
    "title" VARCHAR(255),
    "description" VARCHAR(500),
    "canonical_url" TEXT,
    "no_index" BOOLEAN NOT NULL DEFAULT false,
    "no_follow" BOOLEAN NOT NULL DEFAULT false,
    "structured_data" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "seo_metadata_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."redirects" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" UUID NOT NULL,
    "source_path" TEXT NOT NULL,
    "destination_path" TEXT NOT NULL,
    "status_code" SMALLINT NOT NULL DEFAULT 301,
    "preserve_query" BOOLEAN NOT NULL DEFAULT true,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "starts_at" TIMESTAMPTZ(3),
    "ends_at" TIMESTAMPTZ(3),
    "hit_count" BIGINT NOT NULL DEFAULT 0,
    "last_hit_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "redirects_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "categories_public_id_key" ON "app"."categories"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "categories_slug_key" ON "app"."categories"("slug");

-- CreateIndex
CREATE INDEX "categories_parent_id_idx" ON "app"."categories"("parent_id");

-- CreateIndex
CREATE INDEX "categories_publish_idx" ON "app"."categories"("status", "published_at", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "tags_public_id_key" ON "app"."tags"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "tags_slug_key" ON "app"."tags"("slug");

-- CreateIndex
CREATE INDEX "tags_status_deleted_at_idx" ON "app"."tags"("status", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "products_public_id_key" ON "app"."products"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "products_slug_key" ON "app"."products"("slug");

-- CreateIndex
CREATE INDEX "products_publish_idx" ON "app"."products"("status", "published_at", "deleted_at");

-- CreateIndex
CREATE INDEX "products_featured_idx" ON "app"."products"("is_featured", "status", "published_at");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_public_id_key" ON "app"."product_variants"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_sku_key" ON "app"."product_variants"("sku");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_barcode_key" ON "app"."product_variants"("barcode");

-- CreateIndex
CREATE INDEX "product_variants_product_status_idx" ON "app"."product_variants"("product_id", "status", "position");

-- CreateIndex
CREATE INDEX "product_variants_publish_idx" ON "app"."product_variants"("status", "published_at", "deleted_at");

-- CreateIndex
CREATE INDEX "product_categories_category_idx" ON "app"."product_categories"("category_id", "position");

-- CreateIndex
CREATE INDEX "product_tags_tag_id_idx" ON "app"."product_tags"("tag_id");

-- CreateIndex
CREATE UNIQUE INDEX "media_public_id_key" ON "app"."media"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "media_storage_key_key" ON "app"."media"("storage_key");

-- CreateIndex
CREATE INDEX "media_kind_deleted_at_idx" ON "app"."media"("kind", "deleted_at");

-- CreateIndex
CREATE INDEX "product_media_product_role_idx" ON "app"."product_media"("product_id", "role", "position");

-- CreateIndex
CREATE INDEX "product_media_variant_idx" ON "app"."product_media"("variant_id", "position");

-- CreateIndex
CREATE INDEX "product_media_media_id_idx" ON "app"."product_media"("media_id");

-- CreateIndex
CREATE UNIQUE INDEX "prices_public_id_key" ON "app"."prices"("public_id");

-- CreateIndex
CREATE INDEX "prices_lookup_idx" ON "app"."prices"("variant_id", "currency", "country_code", "is_active");

-- CreateIndex
CREATE INDEX "prices_window_idx" ON "app"."prices"("is_active", "starts_at", "ends_at");

-- CreateIndex
CREATE UNIQUE INDEX "inquiries_public_id_key" ON "app"."inquiries"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "inquiries_inquiry_number_key" ON "app"."inquiries"("inquiry_number");

-- CreateIndex
CREATE INDEX "inquiries_customer_created_at_idx" ON "app"."inquiries"("customer_user_id", "created_at");

-- CreateIndex
CREATE INDEX "inquiries_assignee_status_idx" ON "app"."inquiries"("assigned_to_user_id", "status", "updated_at");

-- CreateIndex
CREATE INDEX "inquiries_order_id_idx" ON "app"."inquiries"("order_id");

-- CreateIndex
CREATE INDEX "inquiries_product_id_idx" ON "app"."inquiries"("product_id");

-- CreateIndex
CREATE INDEX "inquiries_status_created_at_idx" ON "app"."inquiries"("status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "whatsapp_contact_intents_public_id_key" ON "app"."whatsapp_contact_intents"("public_id");

-- CreateIndex
CREATE INDEX "whatsapp_contact_intents_user_idx" ON "app"."whatsapp_contact_intents"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "whatsapp_contact_intents_inquiry_id_idx" ON "app"."whatsapp_contact_intents"("inquiry_id");

-- CreateIndex
CREATE INDEX "whatsapp_contact_intents_cart_id_idx" ON "app"."whatsapp_contact_intents"("cart_id");

-- CreateIndex
CREATE INDEX "whatsapp_contact_intents_order_id_idx" ON "app"."whatsapp_contact_intents"("order_id");

-- CreateIndex
CREATE INDEX "whatsapp_contact_intents_product_id_idx" ON "app"."whatsapp_contact_intents"("product_id");

-- CreateIndex
CREATE UNIQUE INDEX "internal_notes_public_id_key" ON "app"."internal_notes"("public_id");

-- CreateIndex
CREATE INDEX "internal_notes_author_created_at_idx" ON "app"."internal_notes"("author_user_id", "created_at");

-- CreateIndex
CREATE INDEX "internal_notes_customer_created_at_idx" ON "app"."internal_notes"("customer_user_id", "created_at");

-- CreateIndex
CREATE INDEX "internal_notes_inquiry_created_at_idx" ON "app"."internal_notes"("inquiry_id", "created_at");

-- CreateIndex
CREATE INDEX "internal_notes_order_created_at_idx" ON "app"."internal_notes"("order_id", "created_at");

-- CreateIndex
CREATE INDEX "internal_notes_payment_created_at_idx" ON "app"."internal_notes"("payment_id", "created_at");

-- CreateIndex
CREATE INDEX "internal_notes_shipment_created_at_idx" ON "app"."internal_notes"("shipment_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "blog_posts_public_id_key" ON "app"."blog_posts"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "blog_posts_slug_key" ON "app"."blog_posts"("slug");

-- CreateIndex
CREATE INDEX "blog_posts_publish_idx" ON "app"."blog_posts"("status", "published_at", "deleted_at");

-- CreateIndex
CREATE INDEX "blog_posts_author_user_id_idx" ON "app"."blog_posts"("author_user_id");

-- CreateIndex
CREATE INDEX "blog_posts_hero_media_id_idx" ON "app"."blog_posts"("hero_media_id");

-- CreateIndex
CREATE UNIQUE INDEX "pages_public_id_key" ON "app"."pages"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "pages_slug_key" ON "app"."pages"("slug");

-- CreateIndex
CREATE INDEX "pages_publish_idx" ON "app"."pages"("status", "published_at", "deleted_at");

-- CreateIndex
CREATE INDEX "pages_author_user_id_idx" ON "app"."pages"("author_user_id");

-- CreateIndex
CREATE INDEX "pages_hero_media_id_idx" ON "app"."pages"("hero_media_id");

-- CreateIndex
CREATE UNIQUE INDEX "faqs_public_id_key" ON "app"."faqs"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "faqs_slug_key" ON "app"."faqs"("slug");

-- CreateIndex
CREATE INDEX "faqs_status_category_idx" ON "app"."faqs"("status", "category", "position");

-- CreateIndex
CREATE INDEX "faqs_author_user_id_idx" ON "app"."faqs"("author_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "navigations_public_id_key" ON "app"."navigations"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "navigations_key_key" ON "app"."navigations"("key");

-- CreateIndex
CREATE INDEX "navigations_status_idx" ON "app"."navigations"("status");

-- CreateIndex
CREATE INDEX "navigation_items_tree_idx" ON "app"."navigation_items"("navigation_id", "parent_id", "position");

-- CreateIndex
CREATE INDEX "navigation_items_parent_id_idx" ON "app"."navigation_items"("parent_id");

-- CreateIndex
CREATE INDEX "navigation_items_page_id_idx" ON "app"."navigation_items"("page_id");

-- CreateIndex
CREATE INDEX "navigation_items_category_id_idx" ON "app"."navigation_items"("category_id");

-- CreateIndex
CREATE INDEX "navigation_items_product_id_idx" ON "app"."navigation_items"("product_id");

-- CreateIndex
CREATE UNIQUE INDEX "carriers_public_id_key" ON "app"."carriers"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "carriers_code_key" ON "app"."carriers"("code");

-- CreateIndex
CREATE INDEX "carriers_is_active_idx" ON "app"."carriers"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "shipments_public_id_key" ON "app"."shipments"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "shipments_shipment_number_key" ON "app"."shipments"("shipment_number");

-- CreateIndex
CREATE INDEX "shipments_order_created_at_idx" ON "app"."shipments"("order_id", "created_at");

-- CreateIndex
CREATE INDEX "shipments_status_updated_at_idx" ON "app"."shipments"("status", "updated_at");

-- CreateIndex
CREATE INDEX "shipments_carrier_id_idx" ON "app"."shipments"("carrier_id");

-- CreateIndex
CREATE UNIQUE INDEX "shipments_carrier_tracking_key" ON "app"."shipments"("carrier_id", "tracking_number");

-- CreateIndex
CREATE UNIQUE INDEX "packages_public_id_key" ON "app"."packages"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "packages_shipment_number_key" ON "app"."packages"("shipment_id", "package_number");

-- CreateIndex
CREATE INDEX "shipment_items_order_item_id_idx" ON "app"."shipment_items"("order_item_id");

-- CreateIndex
CREATE UNIQUE INDEX "tracking_events_public_id_key" ON "app"."tracking_events"("public_id");

-- CreateIndex
CREATE INDEX "tracking_events_shipment_time_idx" ON "app"."tracking_events"("shipment_id", "occurred_at");

-- CreateIndex
CREATE INDEX "tracking_events_status_time_idx" ON "app"."tracking_events"("status", "occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "tracking_events_carrier_event_key" ON "app"."tracking_events"("shipment_id", "carrier_event_id");

-- CreateIndex
CREATE UNIQUE INDEX "inventory_locations_public_id_key" ON "app"."inventory_locations"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "inventory_locations_code_key" ON "app"."inventory_locations"("code");

-- CreateIndex
CREATE INDEX "inventory_locations_is_active_idx" ON "app"."inventory_locations"("is_active");

-- CreateIndex
CREATE INDEX "inventory_levels_location_id_idx" ON "app"."inventory_levels"("location_id");

-- CreateIndex
CREATE UNIQUE INDEX "inventory_levels_variant_location_key" ON "app"."inventory_levels"("variant_id", "location_id");

-- CreateIndex
CREATE UNIQUE INDEX "inventory_movements_public_id_key" ON "app"."inventory_movements"("public_id");

-- CreateIndex
CREATE INDEX "inventory_movements_level_time_idx" ON "app"."inventory_movements"("inventory_level_id", "occurred_at");

-- CreateIndex
CREATE INDEX "inventory_movements_user_id_idx" ON "app"."inventory_movements"("created_by_user_id");

-- CreateIndex
CREATE INDEX "inventory_movements_reference_idx" ON "app"."inventory_movements"("reference_type", "reference_id");

-- CreateIndex
CREATE UNIQUE INDEX "inventory_reservations_public_id_key" ON "app"."inventory_reservations"("public_id");

-- CreateIndex
CREATE INDEX "inventory_reservations_level_status_idx" ON "app"."inventory_reservations"("inventory_level_id", "status", "expires_at");

-- CreateIndex
CREATE INDEX "inventory_reservations_cart_item_id_idx" ON "app"."inventory_reservations"("cart_item_id");

-- CreateIndex
CREATE INDEX "inventory_reservations_order_item_id_idx" ON "app"."inventory_reservations"("order_item_id");

-- CreateIndex
CREATE UNIQUE INDEX "payment_method_configs_method_key" ON "app"."payment_method_configs"("method");

-- CreateIndex
CREATE INDEX "payment_method_configs_setting_key_idx" ON "app"."payment_method_configs"("setting_key");

-- CreateIndex
CREATE INDEX "payment_method_configs_user_id_idx" ON "app"."payment_method_configs"("updated_by_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "payments_public_id_key" ON "app"."payments"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "payments_provider_payment_id_key" ON "app"."payments"("provider_payment_id");

-- CreateIndex
CREATE INDEX "payments_order_created_at_idx" ON "app"."payments"("order_id", "created_at");

-- CreateIndex
CREATE INDEX "payments_status_created_at_idx" ON "app"."payments"("status", "created_at");

-- CreateIndex
CREATE INDEX "payments_method_status_idx" ON "app"."payments"("method", "status");

-- CreateIndex
CREATE UNIQUE INDEX "payment_events_public_id_key" ON "app"."payment_events"("public_id");

-- CreateIndex
CREATE INDEX "payment_events_payment_time_idx" ON "app"."payment_events"("payment_id", "occurred_at");

-- CreateIndex
CREATE INDEX "payment_events_type_time_idx" ON "app"."payment_events"("event_type", "occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "payment_events_provider_event_key" ON "app"."payment_events"("payment_id", "provider_event_id");

-- CreateIndex
CREATE UNIQUE INDEX "manual_payment_proofs_public_id_key" ON "app"."manual_payment_proofs"("public_id");

-- CreateIndex
CREATE INDEX "manual_payment_proofs_payment_idx" ON "app"."manual_payment_proofs"("payment_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "manual_payment_proofs_media_id_idx" ON "app"."manual_payment_proofs"("media_id");

-- CreateIndex
CREATE INDEX "manual_payment_proofs_submitter_idx" ON "app"."manual_payment_proofs"("submitted_by_user_id");

-- CreateIndex
CREATE INDEX "manual_payment_proofs_reviewer_idx" ON "app"."manual_payment_proofs"("reviewed_by_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "carts_public_id_key" ON "app"."carts"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "carts_anonymous_token_hash_key" ON "app"."carts"("anonymous_token_hash");

-- CreateIndex
CREATE INDEX "carts_user_status_updated_at_idx" ON "app"."carts"("user_id", "status", "updated_at");

-- CreateIndex
CREATE INDEX "carts_status_expires_at_idx" ON "app"."carts"("status", "expires_at");

-- CreateIndex
CREATE INDEX "cart_items_cart_deleted_at_idx" ON "app"."cart_items"("cart_id", "deleted_at");

-- CreateIndex
CREATE INDEX "cart_items_variant_id_idx" ON "app"."cart_items"("variant_id");

-- CreateIndex
CREATE UNIQUE INDEX "orders_public_id_key" ON "app"."orders"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "orders_order_number_key" ON "app"."orders"("order_number");

-- CreateIndex
CREATE UNIQUE INDEX "orders_cart_id_key" ON "app"."orders"("cart_id");

-- CreateIndex
CREATE INDEX "orders_user_created_at_idx" ON "app"."orders"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "orders_status_created_at_idx" ON "app"."orders"("status", "created_at");

-- CreateIndex
CREATE INDEX "orders_payment_status_idx" ON "app"."orders"("payment_status", "created_at");

-- CreateIndex
CREATE INDEX "orders_fulfillment_status_idx" ON "app"."orders"("fulfillment_status", "created_at");

-- CreateIndex
CREATE INDEX "order_items_order_id_idx" ON "app"."order_items"("order_id");

-- CreateIndex
CREATE INDEX "order_items_product_id_idx" ON "app"."order_items"("product_id");

-- CreateIndex
CREATE INDEX "order_items_variant_id_idx" ON "app"."order_items"("variant_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_addresses_order_kind_key" ON "app"."order_addresses"("order_id", "kind");

-- CreateIndex
CREATE UNIQUE INDEX "seo_metadata_public_id_key" ON "app"."seo_metadata"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "seo_metadata_product_id_key" ON "app"."seo_metadata"("product_id");

-- CreateIndex
CREATE UNIQUE INDEX "seo_metadata_category_id_key" ON "app"."seo_metadata"("category_id");

-- CreateIndex
CREATE UNIQUE INDEX "seo_metadata_blog_post_id_key" ON "app"."seo_metadata"("blog_post_id");

-- CreateIndex
CREATE UNIQUE INDEX "seo_metadata_page_id_key" ON "app"."seo_metadata"("page_id");

-- CreateIndex
CREATE UNIQUE INDEX "seo_metadata_faq_id_key" ON "app"."seo_metadata"("faq_id");

-- CreateIndex
CREATE INDEX "seo_metadata_open_graph_media_id_idx" ON "app"."seo_metadata"("open_graph_media_id");

-- CreateIndex
CREATE UNIQUE INDEX "redirects_public_id_key" ON "app"."redirects"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "redirects_source_path_key" ON "app"."redirects"("source_path");

-- CreateIndex
CREATE INDEX "redirects_active_window_idx" ON "app"."redirects"("is_active", "starts_at", "ends_at");

-- AddForeignKey
ALTER TABLE "app"."categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "app"."categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_variants" ADD CONSTRAINT "product_variants_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_categories" ADD CONSTRAINT "product_categories_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_categories" ADD CONSTRAINT "product_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "app"."categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_tags" ADD CONSTRAINT "product_tags_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_tags" ADD CONSTRAINT "product_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "app"."tags"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_media" ADD CONSTRAINT "product_media_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_media" ADD CONSTRAINT "product_media_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "app"."product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."product_media" ADD CONSTRAINT "product_media_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "app"."media"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."prices" ADD CONSTRAINT "prices_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "app"."product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inquiries" ADD CONSTRAINT "inquiries_customer_user_id_fkey" FOREIGN KEY ("customer_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inquiries" ADD CONSTRAINT "inquiries_assigned_to_user_id_fkey" FOREIGN KEY ("assigned_to_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inquiries" ADD CONSTRAINT "inquiries_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inquiries" ADD CONSTRAINT "inquiries_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."whatsapp_contact_intents" ADD CONSTRAINT "whatsapp_contact_intents_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."whatsapp_contact_intents" ADD CONSTRAINT "whatsapp_contact_intents_inquiry_id_fkey" FOREIGN KEY ("inquiry_id") REFERENCES "app"."inquiries"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."whatsapp_contact_intents" ADD CONSTRAINT "whatsapp_contact_intents_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "app"."carts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."whatsapp_contact_intents" ADD CONSTRAINT "whatsapp_contact_intents_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."whatsapp_contact_intents" ADD CONSTRAINT "whatsapp_contact_intents_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."internal_notes" ADD CONSTRAINT "internal_notes_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "app"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."internal_notes" ADD CONSTRAINT "internal_notes_customer_user_id_fkey" FOREIGN KEY ("customer_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."internal_notes" ADD CONSTRAINT "internal_notes_inquiry_id_fkey" FOREIGN KEY ("inquiry_id") REFERENCES "app"."inquiries"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."internal_notes" ADD CONSTRAINT "internal_notes_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."internal_notes" ADD CONSTRAINT "internal_notes_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "app"."payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."internal_notes" ADD CONSTRAINT "internal_notes_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "app"."shipments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."blog_posts" ADD CONSTRAINT "blog_posts_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."blog_posts" ADD CONSTRAINT "blog_posts_hero_media_id_fkey" FOREIGN KEY ("hero_media_id") REFERENCES "app"."media"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."pages" ADD CONSTRAINT "pages_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."pages" ADD CONSTRAINT "pages_hero_media_id_fkey" FOREIGN KEY ("hero_media_id") REFERENCES "app"."media"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."faqs" ADD CONSTRAINT "faqs_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."navigation_items" ADD CONSTRAINT "navigation_items_navigation_id_fkey" FOREIGN KEY ("navigation_id") REFERENCES "app"."navigations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."navigation_items" ADD CONSTRAINT "navigation_items_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "app"."navigation_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."navigation_items" ADD CONSTRAINT "navigation_items_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "app"."pages"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."navigation_items" ADD CONSTRAINT "navigation_items_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "app"."categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."navigation_items" ADD CONSTRAINT "navigation_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."shipments" ADD CONSTRAINT "shipments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."shipments" ADD CONSTRAINT "shipments_carrier_id_fkey" FOREIGN KEY ("carrier_id") REFERENCES "app"."carriers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."packages" ADD CONSTRAINT "packages_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "app"."shipments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."shipment_items" ADD CONSTRAINT "shipment_items_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "app"."shipments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."shipment_items" ADD CONSTRAINT "shipment_items_order_item_id_fkey" FOREIGN KEY ("order_item_id") REFERENCES "app"."order_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."tracking_events" ADD CONSTRAINT "tracking_events_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "app"."shipments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inventory_levels" ADD CONSTRAINT "inventory_levels_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "app"."product_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inventory_levels" ADD CONSTRAINT "inventory_levels_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "app"."inventory_locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inventory_movements" ADD CONSTRAINT "inventory_movements_level_id_fkey" FOREIGN KEY ("inventory_level_id") REFERENCES "app"."inventory_levels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inventory_movements" ADD CONSTRAINT "inventory_movements_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inventory_reservations" ADD CONSTRAINT "inventory_reservations_level_id_fkey" FOREIGN KEY ("inventory_level_id") REFERENCES "app"."inventory_levels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inventory_reservations" ADD CONSTRAINT "inventory_reservations_cart_item_id_fkey" FOREIGN KEY ("cart_item_id") REFERENCES "app"."cart_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."inventory_reservations" ADD CONSTRAINT "inventory_reservations_order_item_id_fkey" FOREIGN KEY ("order_item_id") REFERENCES "app"."order_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."payment_method_configs" ADD CONSTRAINT "payment_method_configs_setting_key_fkey" FOREIGN KEY ("setting_key") REFERENCES "app"."site_settings"("key") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."payment_method_configs" ADD CONSTRAINT "payment_method_configs_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."payments" ADD CONSTRAINT "payments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."payment_events" ADD CONSTRAINT "payment_events_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "app"."payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."manual_payment_proofs" ADD CONSTRAINT "manual_payment_proofs_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "app"."payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."manual_payment_proofs" ADD CONSTRAINT "manual_payment_proofs_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "app"."media"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."manual_payment_proofs" ADD CONSTRAINT "manual_payment_proofs_submitter_id_fkey" FOREIGN KEY ("submitted_by_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."manual_payment_proofs" ADD CONSTRAINT "manual_payment_proofs_reviewer_id_fkey" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."carts" ADD CONSTRAINT "carts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."cart_items" ADD CONSTRAINT "cart_items_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "app"."carts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."cart_items" ADD CONSTRAINT "cart_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "app"."product_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."orders" ADD CONSTRAINT "orders_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "app"."carts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."order_items" ADD CONSTRAINT "order_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "app"."product_variants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."order_addresses" ADD CONSTRAINT "order_addresses_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."seo_metadata" ADD CONSTRAINT "seo_metadata_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."seo_metadata" ADD CONSTRAINT "seo_metadata_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "app"."categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."seo_metadata" ADD CONSTRAINT "seo_metadata_blog_post_id_fkey" FOREIGN KEY ("blog_post_id") REFERENCES "app"."blog_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."seo_metadata" ADD CONSTRAINT "seo_metadata_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "app"."pages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."seo_metadata" ADD CONSTRAINT "seo_metadata_faq_id_fkey" FOREIGN KEY ("faq_id") REFERENCES "app"."faqs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."seo_metadata" ADD CONSTRAINT "seo_metadata_open_graph_media_id_fkey" FOREIGN KEY ("open_graph_media_id") REFERENCES "app"."media"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Domain invariants not currently expressible in the Prisma schema language.
-- These constraints keep invalid commerce state out of the database even when
-- writes originate outside the application service layer.
ALTER TABLE "app"."categories"
  ADD CONSTRAINT "categories_position_check" CHECK ("position" >= 0);

ALTER TABLE "app"."products"
  ADD CONSTRAINT "products_publish_state_check" CHECK ("status" <> 'active' OR "published_at" IS NOT NULL);

ALTER TABLE "app"."product_variants"
  ADD CONSTRAINT "product_variants_position_check" CHECK ("position" >= 0),
  ADD CONSTRAINT "product_variants_weight_check" CHECK ("weight_grams" IS NULL OR "weight_grams" > 0),
  ADD CONSTRAINT "product_variants_dimensions_check" CHECK (
    ("length_millimeters" IS NULL OR "length_millimeters" > 0) AND
    ("width_millimeters" IS NULL OR "width_millimeters" > 0) AND
    ("height_millimeters" IS NULL OR "height_millimeters" > 0)
  ),
  ADD CONSTRAINT "product_variants_publish_state_check" CHECK ("status" <> 'active' OR "published_at" IS NOT NULL);

ALTER TABLE "app"."product_categories"
  ADD CONSTRAINT "product_categories_position_check" CHECK ("position" >= 0);

ALTER TABLE "app"."media"
  ADD CONSTRAINT "media_dimensions_check" CHECK (
    ("width" IS NULL OR "width" > 0) AND
    ("height" IS NULL OR "height" > 0) AND
    ("size_bytes" IS NULL OR "size_bytes" >= 0)
  );

ALTER TABLE "app"."product_media"
  ADD CONSTRAINT "product_media_position_check" CHECK ("position" >= 0);

ALTER TABLE "app"."prices"
  ADD CONSTRAINT "prices_amount_minor_check" CHECK ("amount_minor" >= 0),
  ADD CONSTRAINT "prices_window_check" CHECK ("ends_at" IS NULL OR "starts_at" IS NULL OR "ends_at" > "starts_at");

ALTER TABLE "app"."inquiries"
  ADD CONSTRAINT "inquiries_customer_contact_check" CHECK (
    "customer_user_id" IS NOT NULL OR
    NULLIF(BTRIM("customer_email"), '') IS NOT NULL OR
    NULLIF(BTRIM("customer_phone"), '') IS NOT NULL
  );

ALTER TABLE "app"."internal_notes"
  ADD CONSTRAINT "internal_notes_single_target_check" CHECK (
    NUM_NONNULLS("customer_user_id", "inquiry_id", "order_id", "payment_id", "shipment_id") = 1
  );

ALTER TABLE "app"."blog_posts"
  ADD CONSTRAINT "blog_posts_publish_state_check" CHECK ("status" <> 'published' OR "published_at" IS NOT NULL);

ALTER TABLE "app"."pages"
  ADD CONSTRAINT "pages_publish_state_check" CHECK ("status" <> 'published' OR "published_at" IS NOT NULL);

ALTER TABLE "app"."faqs"
  ADD CONSTRAINT "faqs_position_check" CHECK ("position" >= 0),
  ADD CONSTRAINT "faqs_publish_state_check" CHECK ("status" <> 'published' OR "published_at" IS NOT NULL);

ALTER TABLE "app"."navigation_items"
  ADD CONSTRAINT "navigation_items_position_check" CHECK ("position" >= 0),
  ADD CONSTRAINT "navigation_items_not_self_parent_check" CHECK ("parent_id" IS NULL OR "parent_id" <> "id");

ALTER TABLE "app"."shipments"
  ADD CONSTRAINT "shipments_cost_check" CHECK ("shipping_cost_minor" IS NULL OR "shipping_cost_minor" >= 0);

ALTER TABLE "app"."packages"
  ADD CONSTRAINT "packages_number_check" CHECK ("package_number" > 0),
  ADD CONSTRAINT "packages_dimensions_check" CHECK (
    ("weight_grams" IS NULL OR "weight_grams" > 0) AND
    ("length_millimeters" IS NULL OR "length_millimeters" > 0) AND
    ("width_millimeters" IS NULL OR "width_millimeters" > 0) AND
    ("height_millimeters" IS NULL OR "height_millimeters" > 0)
  );

ALTER TABLE "app"."shipment_items"
  ADD CONSTRAINT "shipment_items_quantity_check" CHECK ("quantity" > 0);

ALTER TABLE "app"."inventory_levels"
  ADD CONSTRAINT "inventory_levels_quantities_check" CHECK (
    "on_hand_quantity" >= 0 AND
    "reserved_quantity" >= 0 AND
    "safety_stock_quantity" >= 0
  );

ALTER TABLE "app"."inventory_movements"
  ADD CONSTRAINT "inventory_movements_delta_check" CHECK ("quantity_delta" <> 0),
  ADD CONSTRAINT "inventory_movements_on_hand_check" CHECK ("on_hand_after" >= 0);

ALTER TABLE "app"."inventory_reservations"
  ADD CONSTRAINT "inventory_reservations_quantity_check" CHECK ("quantity" > 0),
  ADD CONSTRAINT "inventory_reservations_source_check" CHECK (NUM_NONNULLS("cart_item_id", "order_item_id") = 1);

ALTER TABLE "app"."payments"
  ADD CONSTRAINT "payments_amount_check" CHECK ("amount_minor" >= 0),
  ADD CONSTRAINT "payments_crypto_amount_check" CHECK ("crypto_amount" IS NULL OR "crypto_amount" > 0),
  ADD CONSTRAINT "payments_exchange_rate_check" CHECK ("exchange_rate" IS NULL OR "exchange_rate" > 0);

ALTER TABLE "app"."payment_events"
  ADD CONSTRAINT "payment_events_amount_check" CHECK ("amount_minor" IS NULL OR "amount_minor" >= 0),
  ADD CONSTRAINT "payment_events_crypto_amount_check" CHECK ("crypto_amount" IS NULL OR "crypto_amount" > 0);

ALTER TABLE "app"."manual_payment_proofs"
  ADD CONSTRAINT "manual_payment_proofs_amount_check" CHECK ("amount_minor" > 0),
  ADD CONSTRAINT "manual_payment_proofs_review_check" CHECK ("status" = 'pending' OR "reviewed_at" IS NOT NULL);

ALTER TABLE "app"."cart_items"
  ADD CONSTRAINT "cart_items_quantity_check" CHECK ("quantity" > 0),
  ADD CONSTRAINT "cart_items_unit_price_check" CHECK ("unit_price_minor" IS NULL OR "unit_price_minor" >= 0);

ALTER TABLE "app"."orders"
  ADD CONSTRAINT "orders_amounts_check" CHECK (
    "subtotal_minor" >= 0 AND
    "discount_minor" >= 0 AND
    "shipping_minor" >= 0 AND
    "tax_minor" >= 0 AND
    "total_minor" >= 0
  ),
  ADD CONSTRAINT "orders_total_check" CHECK (
    "total_minor" = "subtotal_minor" - "discount_minor" + "shipping_minor" + "tax_minor"
  );

ALTER TABLE "app"."order_items"
  ADD CONSTRAINT "order_items_quantities_check" CHECK (
    "quantity" > 0 AND
    "fulfilled_quantity" >= 0 AND
    "fulfilled_quantity" <= "quantity"
  ),
  ADD CONSTRAINT "order_items_amounts_check" CHECK (
    "unit_price_minor" >= 0 AND
    "discount_minor" >= 0 AND
    "tax_minor" >= 0 AND
    "line_total_minor" >= 0
  ),
  ADD CONSTRAINT "order_items_total_check" CHECK (
    "line_total_minor" = ("unit_price_minor" * "quantity") - "discount_minor" + "tax_minor"
  ),
  ADD CONSTRAINT "order_items_weight_check" CHECK ("weight_grams" IS NULL OR "weight_grams" > 0);

ALTER TABLE "app"."seo_metadata"
  ADD CONSTRAINT "seo_metadata_single_entity_check" CHECK (
    NUM_NONNULLS("product_id", "category_id", "blog_post_id", "page_id", "faq_id") = 1
  );

ALTER TABLE "app"."redirects"
  ADD CONSTRAINT "redirects_status_code_check" CHECK ("status_code" IN (301, 302, 307, 308)),
  ADD CONSTRAINT "redirects_source_path_check" CHECK (LEFT("source_path", 1) = '/'),
  ADD CONSTRAINT "redirects_distinct_paths_check" CHECK ("source_path" <> "destination_path"),
  ADD CONSTRAINT "redirects_window_check" CHECK ("ends_at" IS NULL OR "starts_at" IS NULL OR "ends_at" > "starts_at"),
  ADD CONSTRAINT "redirects_hit_count_check" CHECK ("hit_count" >= 0);

-- Partial indexes keep hot operational lookups compact. Prisma does not yet
-- describe partial indexes, so they intentionally live in migration SQL.
CREATE UNIQUE INDEX "carts_one_active_per_user_idx"
  ON "app"."carts" ("user_id")
  WHERE "user_id" IS NOT NULL AND "status" = 'active';

CREATE INDEX "prices_active_lookup_idx"
  ON "app"."prices" ("variant_id", "currency", "country_code", "starts_at", "ends_at")
  WHERE "is_active" = true AND "deleted_at" IS NULL;

CREATE INDEX "inventory_reservations_active_expiry_idx"
  ON "app"."inventory_reservations" ("expires_at", "inventory_level_id")
  WHERE "status" = 'active';

CREATE INDEX "inquiries_open_assignment_idx"
  ON "app"."inquiries" ("assigned_to_user_id", "updated_at")
  WHERE "status" IN ('open', 'in_progress', 'waiting_customer');
