CREATE TYPE "app"."price_mode" AS ENUM ('fixed', 'on_request');
CREATE TYPE "app"."data_quality_status" AS ENUM ('verified', 'review_required');

ALTER TABLE "app"."categories"
  ADD COLUMN "legacy_source_id" VARCHAR(220),
  ADD COLUMN "source_hash" VARCHAR(64),
  ADD COLUMN "legacy_metadata" JSONB;

ALTER TABLE "app"."products"
  ADD COLUMN "legacy_source_id" VARCHAR(220),
  ADD COLUMN "source_hash" VARCHAR(64),
  ADD COLUMN "short_description" TEXT,
  ADD COLUMN "purity" VARCHAR(80),
  ADD COLUMN "cas_number" VARCHAR(160),
  ADD COLUMN "appearance" TEXT,
  ADD COLUMN "storage_instructions" TEXT,
  ADD COLUMN "legacy_metadata" JSONB,
  ADD COLUMN "data_quality_status" "app"."data_quality_status" NOT NULL DEFAULT 'review_required',
  ADD COLUMN "position" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "app"."product_variants"
  ALTER COLUMN "sku" DROP NOT NULL,
  ADD COLUMN "price_mode" "app"."price_mode" NOT NULL DEFAULT 'fixed';

ALTER TABLE "app"."order_items"
  ALTER COLUMN "sku" DROP NOT NULL;

ALTER TABLE "app"."blog_posts"
  ADD COLUMN "legacy_source_id" VARCHAR(220),
  ADD COLUMN "source_hash" VARCHAR(64),
  ADD COLUMN "category" VARCHAR(160),
  ADD COLUMN "author_display_name" VARCHAR(255),
  ADD COLUMN "reading_minutes" INTEGER,
  ADD COLUMN "content_data" JSONB;

CREATE TABLE "app"."merchandising_placements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "key" VARCHAR(100) NOT NULL,
  "product_id" BIGINT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "metadata" JSONB,
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "merchandising_placements_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "merchandising_placements_product_id_fkey"
    FOREIGN KEY ("product_id") REFERENCES "app"."products"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "categories_legacy_source_id_key"
  ON "app"."categories"("legacy_source_id");
CREATE UNIQUE INDEX "products_legacy_source_id_key"
  ON "app"."products"("legacy_source_id");
CREATE INDEX "products_cas_number_idx" ON "app"."products"("cas_number");
CREATE INDEX "products_quality_status_idx"
  ON "app"."products"("data_quality_status", "status");
CREATE UNIQUE INDEX "blog_posts_legacy_source_id_key"
  ON "app"."blog_posts"("legacy_source_id");
CREATE UNIQUE INDEX "merchandising_placements_key_product_key"
  ON "app"."merchandising_placements"("key", "product_id");
CREATE INDEX "merchandising_placements_key_position_idx"
  ON "app"."merchandising_placements"("key", "position");
CREATE INDEX "merchandising_placements_product_id_idx"
  ON "app"."merchandising_placements"("product_id");

ALTER TABLE "app"."categories"
  ADD CONSTRAINT "categories_source_hash_check"
    CHECK ("source_hash" IS NULL OR "source_hash" ~ '^[0-9a-f]{64}$');
ALTER TABLE "app"."products"
  ADD CONSTRAINT "products_source_hash_check"
    CHECK ("source_hash" IS NULL OR "source_hash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "products_position_check" CHECK ("position" >= 0);
ALTER TABLE "app"."blog_posts"
  ADD CONSTRAINT "blog_posts_source_hash_check"
    CHECK ("source_hash" IS NULL OR "source_hash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "blog_posts_reading_minutes_check"
    CHECK ("reading_minutes" IS NULL OR "reading_minutes" > 0);
ALTER TABLE "app"."merchandising_placements"
  ADD CONSTRAINT "merchandising_placements_position_check"
    CHECK ("position" >= 0);
