export const CATALOG_IMPORT_MAX_BYTES = 2 * 1024 * 1024;
export const CATALOG_IMPORT_MAX_ROWS = 1_000;
export const CATALOG_IMPORT_MAX_CATEGORY_ASSIGNMENTS = 10_000;
export const CATALOG_IMPORT_CONFIRMATION = "APPLY CATALOG IMPORT";
