import { randomUUID } from "node:crypto";

import type { Metadata } from "next";
import Link from "next/link";
import { connection } from "next/server";

import { AdminActionForm } from "@/app/admin/_components/AdminActionForm";
import { createCustomRoleAction } from "@/app/admin/users/roles/actions";
import { RolePermissionSelector } from "@/app/admin/users/roles/RolePermissionSelector";
import { getCustomRoleCreateContext } from "@/server/admin/access/role-queries";

export const metadata: Metadata = {
  title: "Create custom administrator role",
  robots: { index: false, follow: false },
};

const inputClass =
  "mt-2 w-full rounded-xl border border-ink-900/15 bg-white px-4 py-3 text-sm text-strong outline-none focus:border-sage-600";
const labelClass = "block text-sm font-semibold text-strong";

export default async function CreateCustomRolePage() {
  await connection();
  const { permissionOptions } = await getCustomRoleCreateContext();

  return (
    <section className="section-y bg-surface-warm">
      <div className="container-x max-w-5xl">
        <header>
          <Link
            href="/admin/users/roles"
            className="text-sm font-semibold text-sage-700"
          >
            ← Roles and permissions
          </Link>
          <p className="mt-6 font-mono text-eyebrow uppercase text-sage-600">
            Custom administrator role
          </p>
          <h1 className="mt-3 text-h2 text-strong">Create custom role</h1>
          <p className="mt-3 max-w-3xl text-body">
            Start with the smallest permission set needed for the job. The stable
            internal identifier is generated by the server and cannot be edited.
          </p>
        </header>

        <article className="mt-10 rounded-2xl border border-ink-900/[0.08] bg-surface p-7">
          <AdminActionForm
            action={createCustomRoleAction}
            submitLabel="Create custom role"
          >
            <input type="hidden" name="submissionId" value={randomUUID()} />
            <label className={labelClass}>
              Role name
              <input
                className={inputClass}
                name="name"
                required
                minLength={2}
                maxLength={120}
                autoComplete="off"
              />
            </label>
            <label className={labelClass}>
              Description
              <textarea
                className={inputClass}
                name="description"
                rows={5}
                maxLength={2000}
              />
            </label>
            <RolePermissionSelector
              options={permissionOptions.map((permission) => ({
                ...permission,
                actorGranted: true,
                selected: permission.slug === "admin.access",
              }))}
            />
          </AdminActionForm>
        </article>
      </div>
    </section>
  );
}
